[package]
name = "philosopher_chopstick"
version = "0.1.0"
authors = ["Frank Moreno <frankmoreno1993@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
